/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import javax.swing.JScrollBar;

/**
 *
 * @author mthuan
 */
public class LeftMess extends javax.swing.JPanel {

    /**
     * Creates new form LeftMess
     */
    public LeftMess() {
        initComponents();
        initDisplay();

    }

    public LeftMess(String name, String chats) {
        initComponents();
        initDisplay();

        username.setText(name);
        content.setText(chats);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPane = new javax.swing.JPanel();
        textPanel = new javax.swing.JPanel();
        scrollText = new javax.swing.JScrollPane();
        content = new javax.swing.JTextArea();
        usernamePanel = new javax.swing.JPanel();
        username = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(152, 55, 254)));
        setPreferredSize(new java.awt.Dimension(480, 161));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        contentPane.setBackground(new java.awt.Color(254, 254, 254));
        contentPane.setPreferredSize(new java.awt.Dimension(400, 159));
        contentPane.setLayout(new java.awt.BorderLayout());

        scrollText.setBorder(null);

        content.setBackground(new java.awt.Color(254, 254, 254));
        content.setColumns(20);
        content.setRows(5);
        scrollText.setViewportView(content);

        javax.swing.GroupLayout textPanelLayout = new javax.swing.GroupLayout(textPanel);
        textPanel.setLayout(textPanelLayout);
        textPanelLayout.setHorizontalGroup(
            textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollText, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        textPanelLayout.setVerticalGroup(
            textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollText, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
        );

        contentPane.add(textPanel, java.awt.BorderLayout.CENTER);

        usernamePanel.setBackground(new java.awt.Color(254, 254, 254));
        usernamePanel.setPreferredSize(new java.awt.Dimension(395, 40));

        username.setFont(new java.awt.Font("Arimo", 1, 24)); // NOI18N
        username.setForeground(new java.awt.Color(115, 82, 246));
        username.setText("jLabel1");

        javax.swing.GroupLayout usernamePanelLayout = new javax.swing.GroupLayout(usernamePanel);
        usernamePanel.setLayout(usernamePanelLayout);
        usernamePanelLayout.setHorizontalGroup(
            usernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usernamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
        );
        usernamePanelLayout.setVerticalGroup(
            usernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        contentPane.add(usernamePanel, java.awt.BorderLayout.PAGE_START);

        add(contentPane);

        jPanel3.setBackground(new java.awt.Color(254, 254, 254));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );

        add(jPanel3);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea content;
    private javax.swing.JPanel contentPane;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane scrollText;
    private javax.swing.JPanel textPanel;
    private javax.swing.JLabel username;
    private javax.swing.JPanel usernamePanel;
    // End of variables declaration//GEN-END:variables

    private void initDisplay() {
        content.setEditable(false);
        content.setLineWrap(true);
        scrollText.getViewport().setBackground(Color.WHITE);
        JScrollBar vertical = scrollText.getVerticalScrollBar();
        vertical.setValue(0);
        
    }
}
